# Generated by Django 6.0.5 on 2026-06-29 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CARTAO_CREDITO', 'Cartão de crédito'), ('CARTAO_DEBITO', 'Cartão de débito'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA', 'Transferência'), ('OUTROS', 'Outros')], max_length=30)),
                ('fixa', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='finances.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finances_despesa',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
